image: Visual Studio 2015

platform:
- x64

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

configuration:
  - Debug
  - Release

# see http://www.appveyor.com/docs/installed-software
environment:
  global:
    BUILD_CONF: $(configuration)
  matrix:
  - QTDIR: C:\Qt\5.7\msvc2015
    PATH: C:\Qt\5.7\msvc2015\bin;%PATH%
    CMAKE_GENERATOR: "Visual Studio 14 2015"
  - QTDIR: C:\Qt\5.7\msvc2015_64
    PATH: C:\Qt\5.7\msvc2015_64\bin;%PATH%
    CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
  
build_script:
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake -G "%CMAKE_GENERATOR%" ..
- cmake --build . --config %BUILD_CONF% -- /clp:ErrorsOnly
